'use client'
import {useEffect,useMemo,useState} from 'react'
import {useRouter} from 'next/navigation'
import {supabase} from '../lib/supabase'
const today=()=>{const d=new Date();const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}, N=(x:any)=>Number(x||0)
const validDate=(v:any)=>{
  if(!v || typeof v!=='string') return null
  if(!/^\d{4}-\d{2}-\d{2}$/.test(v)) return null
  const [y,m,d]=v.split('-').map(Number)
  if(y<1900 || y>2100 || m<1 || m>12 || d<1 || d>31) return null
  const dt=new Date(`${v}T00:00:00`)
  if(Number.isNaN(dt.getTime())) return null
  if(dt.getFullYear()!==y || dt.getMonth()+1!==m || dt.getDate()!==d) return null
  return v
}
const dateOrNull=(v:any)=>validDate(v)
export default function Home(){
 const router=useRouter(); const [tab,setTab]=useState('overview'),[loading,setLoading]=useState(true),[me,setMe]=useState<any>(null)
 const [profiles,setProfiles]=useState<any[]>([]),[clients,setClients]=useState<any[]>([]),[packages,setPackages]=useState<any[]>([]),[tasks,setTasks]=useState<any[]>([]),[txs,setTxs]=useState<any[]>([]),[appts,setAppts]=useState<any[]>([])
 const [client,setClient]=useState<any>({name:'',package_id:'',start_date:today(),end_date:'',contract_value:'',outstanding:'',phone:'',logo_url:''})
 const [pkg,setPkg]=useState<any>({name:'',price:'',posts_target:'0',reels_target:'0',daily_story:false,image_url:''})
 const [task,setTask]=useState<any>({title:'',client_id:'',due_date:today(),priority:'normal'})
 const [tx,setTx]=useState<any>({title:'',client_id:'',type:'income',amount:'',transaction_date:today()})
 const [appt,setAppt]=useState<any>({title:'',client_id:'',appointment_date:today(),appointment_time:''})
 const cname=(id:any)=>clients.find(c=>c.id===id)?.name||'عام'
 async function load(){const {data:{session}}=await supabase.auth.getSession();if(!session){router.replace('/login');return}
  const [p,c,g,t,f,a]=await Promise.all([supabase.from('profiles').select('*'),supabase.from('clients').select('*').order('created_at'),supabase.from('packages').select('*').order('created_at'),supabase.from('tasks').select('*').order('due_date'),supabase.from('financial_transactions').select('*').order('transaction_date',{ascending:false}),supabase.from('appointments').select('*').order('appointment_date')])
  setProfiles(p.data||[]);setMe((p.data||[]).find((x:any)=>x.id===session.user.id)||{display_name:session.user.email});setClients(c.data||[]);setPackages(g.data||[]);setTasks(t.data||[]);setTxs(f.data||[]);setAppts(a.data||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 async function add(table:string,p:any,reset:()=>void){const {error}=await supabase.from(table).insert(p);if(error)return alert(error.message);reset();load()}
 async function del(table:string,id:string){if(!confirm('متأكد من الحذف؟'))return;const {error}=await supabase.from(table).delete().eq('id',id);if(error)return alert(error.message);load()}
 async function edit(table:string,row:any,fields:string[]){let p:any={};for(const k of fields){const v=prompt(`تعديل ${k}`,row[k]??'');if(v===null)continue
  if(['start_date','end_date','due_date','transaction_date','appointment_date'].includes(k)){
    if(v!=='' && !validDate(v)){alert(`التاريخ غير صحيح: ${v}\nاستخدم YYYY-MM-DD`);return}
    p[k]=dateOrNull(v); continue
  }
  p[k]=['price','amount','contract_value','outstanding','posts_target','reels_target'].includes(k)?(v===''?null:Number(v)):v
}if(!Object.keys(p).length)return;const {error}=await supabase.from(table).update(p).eq('id',row.id);if(error)return alert(error.message);load()}
 async function upload(file:File,folder:string){const ext=file.name.split('.').pop();const path=`${folder}/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from('dh-manager-media').upload(path,file);if(error)throw error;return supabase.storage.from('dh-manager-media').getPublicUrl(path).data.publicUrl}
 const income=txs.filter(x=>x.type==='income').reduce((s,x)=>s+N(x.amount),0),expenses=txs.filter(x=>x.type!=='income').reduce((s,x)=>s+N(x.amount),0)
 if(loading)return <main className="shell">جاري تحميل DH Manager...</main>
 const tabs=[['overview','Overview'],['clients','Clients'],['packages','Packages'],['tasks','Tasks'],['finance','Finance'],['calendar','Calendar']]
 return <main className="shell" dir="rtl"><header className="topbar"><div className="brand"><img src="/dh-logo-transparent.png"/><div><div className="eyebrow">SOCIAL • CONTENT • MARKETING</div><h1>DH <span>Manager</span></h1><div className="muted">DH AGENCY OPERATIONS</div></div></div><div className="user"><div className="avatar">{(me?.display_name||'U')[0]}</div><div><b>{me?.display_name||'USER'}</b><div className="muted">{me?.role||'TEAM'}</div></div><button className="btn" onClick={async()=>{await supabase.auth.signOut();router.replace('/login')}}>خروج</button></div></header>
 <nav className="nav">{tabs.map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</nav>
 {tab==='overview'&&<>
 <section className="hero"><div className="heroCopy"><span className="heroKicker">DH COMMAND CENTER</span><h2>Good evening, {String(me?.display_name||'Hatem').split(' ')[0]} 👋</h2><p>Discipline today, results tomorrow.</p><div className="quick"><button className="btn primary" onClick={()=>setTab('clients')}>＋ Create Client</button><button className="btn" onClick={()=>setTab('tasks')}>＋ Task</button><button className="btn" onClick={()=>setTab('finance')}>＋ Invoice</button></div></div><div className="heroMark"><img src="/dh-logo-transparent.png"/><span>IDEAS<br/>STRATEGY<br/><b>RESULTS</b></span></div></section><section className="metrics"><div className="metric"><small>العملاء</small><strong>{clients.length}</strong><span>إجمالي العملاء</span></div><div className="metric"><small>المهام المفتوحة</small><strong>{tasks.filter(x=>x.status!=='completed').length}</strong><span>قيد المتابعة</span></div><div className="metric"><small>الدخل</small><strong>{income} JD</strong><span>إجمالي المسجل</span></div><div className="metric"><small>الصافي</small><strong>{income-expenses} JD</strong><span>دخل - مصاريف</span></div></section><section className="grid2"><div className="panel"><div className="panelHead"><h2>العملاء</h2><span className="pill">LIVE</span></div><div className="list">{clients.slice(0,7).map(c=><div className="row" key={c.id}>{c.logo_url?<img className="logo" src={c.logo_url}/>:<div className="avatar">{c.name?.[0]}</div>}<div className="grow"><b>{c.name}</b><span>{c.package_name||'بدون باقة'} • {c.start_date||'-'} → {c.end_date||'-'}</span></div></div>)}</div></div><div className="panel"><div className="panelHead"><h2>آخر المهام</h2><span className="pill">TEAM</span></div><div className="list">{tasks.slice(0,7).map(t=><div className="row" key={t.id}><div className="grow"><b>{t.title}</b><span>{cname(t.client_id)} • {t.due_date||'-'}</span></div><span className="pill">{t.priority}</span></div>)}</div></div></section></>}
 {tab==='clients'&&<section className="panel"><div className="panelHead"><h2>العملاء</h2><span className="pill">ADD • EDIT • DELETE • IMAGE</span></div><div className="form"><input placeholder="اسم العميل" value={client.name} onChange={e=>setClient({...client,name:e.target.value})}/><select value={client.package_id} onChange={e=>setClient({...client,package_id:e.target.value})}><option value="">اختر الباقة</option>{packages.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><input type="date" value={client.start_date} onChange={e=>setClient({...client,start_date:e.target.value})}/><input type="date" value={client.end_date} onChange={e=>setClient({...client,end_date:e.target.value})}/><input type="number" placeholder="قيمة العقد" value={client.contract_value} onChange={e=>setClient({...client,contract_value:e.target.value})}/><input type="number" placeholder="المتبقي" value={client.outstanding} onChange={e=>setClient({...client,outstanding:e.target.value})}/><input placeholder="رقم الهاتف" value={client.phone} onChange={e=>setClient({...client,phone:e.target.value})}/><input type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f)try{setClient({...client,logo_url:await upload(f,'clients')})}catch(x:any){alert(x.message)}}}/><button className="btn primary" onClick={()=>{const p=packages.find(x=>x.id===client.package_id);add('clients',{...client,start_date:dateOrNull(client.start_date),end_date:dateOrNull(client.end_date),package_id:client.package_id||null,package_name:p?.name||null,contract_value:client.contract_value===''?null:Number(client.contract_value),outstanding:client.outstanding===''?null:Number(client.outstanding),logo_url:client.logo_url||null,status:'active'},()=>setClient({name:'',package_id:'',start_date:today(),end_date:'',contract_value:'',outstanding:'',phone:'',logo_url:''}))}}>إضافة عميل</button></div><div className="cards">{clients.map(c=><article className="card" key={c.id}><div className="clientTop"><div>{c.logo_url?<img className="logo" src={c.logo_url}/>:<div className="avatar">{c.name?.[0]}</div>}<h3>{c.name}</h3></div><span className="pill">{c.package_name||'بدون باقة'}</span></div><p className="muted">{c.start_date||'-'} → {c.end_date||'-'}</p><div className="money">العقد: {c.contract_value??'-'} JD • المتبقي: {c.outstanding??'-'} JD</div><div className="actions"><button className="btn" onClick={()=>edit('clients',c,['name','start_date','end_date','contract_value','outstanding','phone'])}>تعديل</button><button className="btn danger" onClick={()=>del('clients',c.id)}>حذف</button></div></article>)}</div></section>}
 {tab==='packages'&&<section className="panel"><h2>الباقات</h2><div className="form"><input placeholder="اسم الباقة" value={pkg.name} onChange={e=>setPkg({...pkg,name:e.target.value})}/><input type="number" placeholder="السعر" value={pkg.price} onChange={e=>setPkg({...pkg,price:e.target.value})}/><input type="number" placeholder="Posts" value={pkg.posts_target} onChange={e=>setPkg({...pkg,posts_target:e.target.value})}/><input type="number" placeholder="Reels" value={pkg.reels_target} onChange={e=>setPkg({...pkg,reels_target:e.target.value})}/><input type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f)try{setPkg({...pkg,image_url:await upload(f,'packages')})}catch(x:any){alert(x.message)}}}/><button className="btn primary" onClick={()=>add('packages',{...pkg,price:pkg.price===''?null:Number(pkg.price),posts_target:Number(pkg.posts_target),reels_target:Number(pkg.reels_target),image_url:pkg.image_url||null},()=>setPkg({name:'',price:'',posts_target:'0',reels_target:'0',daily_story:false,image_url:''}))}>إضافة باقة</button></div><div className="cards">{packages.map(p=><article className="card" key={p.id}>{p.image_url&&<img className="pkgimg" src={p.image_url}/>}<h3>{p.name}</h3><div className="money">{p.price??'-'} JD</div><p>{p.posts_target} Posts • {p.reels_target} Reels</p><div className="actions"><button className="btn" onClick={()=>edit('packages',p,['name','price','posts_target','reels_target'])}>تعديل</button><button className="btn danger" onClick={()=>del('packages',p.id)}>حذف</button></div></article>)}</div></section>}
 {tab==='tasks'&&<section className="panel"><h2>المهام</h2><div className="form"><input placeholder="المهمة" value={task.title} onChange={e=>setTask({...task,title:e.target.value})}/><select value={task.client_id} onChange={e=>setTask({...task,client_id:e.target.value})}><option value="">عام</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input type="date" value={task.due_date} onChange={e=>setTask({...task,due_date:e.target.value})}/><select value={task.priority} onChange={e=>setTask({...task,priority:e.target.value})}><option value="normal">عادي</option><option value="medium">متوسط</option><option value="high">عالي</option></select><button className="btn primary" onClick={()=>add('tasks',{...task,due_date:dateOrNull(task.due_date),client_id:task.client_id||null,status:'pending'},()=>setTask({title:'',client_id:'',due_date:today(),priority:'normal'}))}>إضافة</button></div><div className="list">{tasks.map(t=><div className="row" key={t.id}><div className="grow"><b>{t.title}</b><span>{cname(t.client_id)} • {t.due_date}</span></div><button className="btn" onClick={()=>edit('tasks',t,['title','due_date','priority'])}>تعديل</button><button className="btn danger" onClick={()=>del('tasks',t.id)}>حذف</button></div>)}</div></section>}
 {tab==='finance'&&<section className="panel"><h2>المالية</h2><div className="form"><input placeholder="البيان" value={tx.title} onChange={e=>setTx({...tx,title:e.target.value})}/><select value={tx.type} onChange={e=>setTx({...tx,type:e.target.value})}><option value="income">دخل</option><option value="expense">مصروف</option><option value="freelancer">فريلانسر</option></select><input type="number" placeholder="المبلغ" value={tx.amount} onChange={e=>setTx({...tx,amount:e.target.value})}/><button className="btn primary" onClick={()=>add('financial_transactions',{...tx,transaction_date:dateOrNull(tx.transaction_date)||today(),client_id:null,amount:Number(tx.amount||0)},()=>setTx({title:'',client_id:'',type:'income',amount:'',transaction_date:today()}))}>إضافة</button></div><div className="list">{txs.map(x=><div className="row" key={x.id}><div className="grow"><b>{x.title}</b><span>{x.transaction_date}</span></div><b className={x.type==='income'?'money':'red'}>{x.amount} JD</b><button className="btn" onClick={()=>edit('financial_transactions',x,['title','amount','transaction_date'])}>تعديل</button><button className="btn danger" onClick={()=>del('financial_transactions',x.id)}>حذف</button></div>)}</div></section>}
 {tab==='calendar'&&<section className="panel"><h2>المواعيد</h2><div className="form"><input placeholder="اسم الموعد" value={appt.title} onChange={e=>setAppt({...appt,title:e.target.value})}/><input type="date" value={appt.appointment_date} onChange={e=>setAppt({...appt,appointment_date:e.target.value})}/><input type="time" value={appt.appointment_time} onChange={e=>setAppt({...appt,appointment_time:e.target.value})}/><button className="btn primary" onClick={()=>add('appointments',{...appt,appointment_date:dateOrNull(appt.appointment_date)||today(),appointment_time:appt.appointment_time||null,client_id:null,status:'pending'},()=>setAppt({title:'',client_id:'',appointment_date:today(),appointment_time:''}))}>إضافة</button></div><div className="list">{appts.map(a=><div className="row" key={a.id}><div className="grow"><b>{a.title}</b><span>{a.appointment_date} {a.appointment_time}</span></div><button className="btn" onClick={()=>edit('appointments',a,['title','appointment_date','appointment_time'])}>تعديل</button><button className="btn danger" onClick={()=>del('appointments',a.id)}>حذف</button></div>)}</div></section>}
 </main>}
