'use client'
import {useEffect,useMemo,useState} from 'react'
import {useRouter} from 'next/navigation'
import {supabase} from '../lib/supabase'

const today=()=>new Date().toISOString().slice(0,10), N=(x:any)=>Number(x||0)
const validDate=(v:any)=>{if(!v||typeof v!=='string'||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(v))return null;const [y,m,d]=v.split('-').map(Number);const dt=new Date(`${v}T00:00:00`);return y>=1900&&y<=2100&&m>0&&m<13&&d>0&&d<32&&!Number.isNaN(dt.getTime())&&dt.getFullYear()===y&&dt.getMonth()+1===m&&dt.getDate()===d?v:null}
const dateOrNull=(v:any)=>validDate(v)
const fmt=(v:any)=>{if(!v)return '-';const [y,m,d]=String(v).slice(0,10).split('-');return `${Number(d)}/${Number(m)}/${y}`}
const I=({children}:{children:any})=><span className="ico">{children}</span>

export default function Home(){
 const router=useRouter(); const [tab,setTab]=useState('overview'),[loading,setLoading]=useState(true),[me,setMe]=useState<any>(null),[search,setSearch]=useState('')
 const [profiles,setProfiles]=useState<any[]>([]),[clients,setClients]=useState<any[]>([]),[packages,setPackages]=useState<any[]>([]),[tasks,setTasks]=useState<any[]>([]),[txs,setTxs]=useState<any[]>([]),[appts,setAppts]=useState<any[]>([]),[logs,setLogs]=useState<any[]>([])
 const [client,setClient]=useState<any>({name:'',package_id:'',start_date:today(),end_date:'',contract_value:'',outstanding:'',phone:'',logo_url:''})
 const [pkg,setPkg]=useState<any>({name:'',price:'',posts_target:'0',reels_target:'0',daily_story:false,image_url:''})
 const [task,setTask]=useState<any>({title:'',client_id:'',due_date:today(),priority:'normal'})
 const [tx,setTx]=useState<any>({title:'',client_id:'',type:'income',amount:'',transaction_date:today()})
 const [appt,setAppt]=useState<any>({title:'',client_id:'',appointment_date:today(),appointment_time:''})
 const cname=(id:any)=>clients.find(c=>c.id===id)?.name||'عام'
 async function load(){const {data:{session}}=await supabase.auth.getSession();if(!session){router.replace('/login');return}
  const [p,c,g,t,f,a,l]=await Promise.all([supabase.from('profiles').select('*'),supabase.from('clients').select('*').order('created_at'),supabase.from('packages').select('*').order('created_at'),supabase.from('tasks').select('*').order('due_date'),supabase.from('financial_transactions').select('*').order('transaction_date',{ascending:false}),supabase.from('appointments').select('*').order('appointment_date'),supabase.from('activity_logs').select('*').order('created_at',{ascending:false}).limit(20)])
  setProfiles(p.data||[]);setMe((p.data||[]).find((x:any)=>x.id===session.user.id)||{display_name:session.user.email});setClients(c.data||[]);setPackages(g.data||[]);setTasks(t.data||[]);setTxs(f.data||[]);setAppts(a.data||[]);setLogs(l.data||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 async function add(table:string,p:any,reset:()=>void){const payload:any={...p};for(const k of ['start_date','end_date','due_date','transaction_date','appointment_date'])if(k in payload)payload[k]=payload[k]?dateOrNull(payload[k]):null;const {error}=await supabase.from(table).insert(payload);if(error)return alert(error.message);reset();load()}
 async function del(table:string,id:string){if(!confirm('متأكد من الحذف؟'))return;const {error}=await supabase.from(table).delete().eq('id',id);if(error)return alert(error.message);load()}
 async function edit(table:string,row:any,fields:string[]){let p:any={};for(const k of fields){const v=prompt(`تعديل ${k}`,row[k]??'');if(v===null)continue;if(['start_date','end_date','due_date','transaction_date','appointment_date'].includes(k)){if(v!==''&&!validDate(v)){alert('استخدم التاريخ YYYY-MM-DD');return}p[k]=dateOrNull(v);continue}p[k]=['price','amount','contract_value','outstanding','posts_target','reels_target'].includes(k)?(v===''?null:Number(v)):v}if(!Object.keys(p).length)return;const {error}=await supabase.from(table).update(p).eq('id',row.id);if(error)return alert(error.message);load()}
 async function upload(file:File,folder:string){const ext=file.name.split('.').pop();const path=`${folder}/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from('dh-manager-media').upload(path,file);if(error)throw error;return supabase.storage.from('dh-manager-media').getPublicUrl(path).data.publicUrl}
 const income=txs.filter(x=>x.type==='income').reduce((s,x)=>s+N(x.amount),0), expenses=txs.filter(x=>x.type!=='income').reduce((s,x)=>s+N(x.amount),0), pending=tasks.filter(x=>x.status!=='completed').length
 const filtered=useMemo(()=>clients.filter(c=>!search||`${c.name} ${c.package_name||''}`.toLowerCase().includes(search.toLowerCase())),[clients,search])
 if(loading)return <main className="loading">DH MANAGER <span>LOADING...</span></main>
 const menu=[['overview','⌂','Dashboard'],['clients','♟','Clients'],['packages','◇','Packages'],['tasks','☑','Tasks'],['content','▧','Content'],['finance','$','Finance'],['calendar','▦','Calendar'],['team','♟','Team'],['activity','◴','Activity Log'],['settings','⚙','Settings']]
 const pageTitle:any={clients:'Clients',packages:'Packages',tasks:'Tasks',content:'Content',finance:'Finance',calendar:'Calendar',team:'Team',activity:'Activity Log',settings:'Settings'}
 return <main className="app" dir="ltr">
  <aside className="sidebar">
   <div className="sideLogo"><img src="/dh-agency-logo.jpeg"/></div>
   <nav>{menu.map(m=><button key={m[0]} className={tab===m[0]?'active':''} onClick={()=>setTab(m[0])}><I>{m[1]}</I><span>{m[2]}</span></button>)}</nav>
   <div className="sideSlogan"><span>BIGGER</span><b>BRANDS</b><span>BRIGHTER</span><strong>RESULTS</strong></div>
  </aside>
  <section className="workspace">
   <header className="header"><div className="wordmark"><b>DH AGENCY</b><span>SOCIAL <i/> CONTENT <em/> MARKETING</span></div><div className="headRight"><div className="search">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search clients, tasks, content ..."/></div><div className="bell">♧<i/></div><div className="profile"><div className="profilePic">{(me?.display_name||'U')[0]}</div><div><b>{me?.display_name||'USER'}</b><span>{me?.role||'TEAM'}</span></div><button onClick={async()=>{await supabase.auth.signOut();router.replace('/login')}}>⌄</button></div></div></header>
   {tab==='overview'?<Dashboard/>:<Page/>}
   <footer><span>© 2026 DH Agency. All rights reserved.</span><b>SOCIAL <i/> CONTENT <em/> MARKETING</b></footer>
  </section>
 </main>

 function Dashboard(){return <div className="dash">
  <section className="hero"><div className="quote">“From Ideas<br/>to <b>Real</b> <strong>Impact</strong>”</div><div className="heroLogo"><img src="/dh-agency-logo.jpeg"/></div><div className="ideas">IDEAS<br/>STRATEGY<br/><b>RESULTS</b></div><div className="datebox">▣ &nbsp; Thu, 18 Sep 2026</div></section>
  <section className="kpis"><Kpi icon="♟" n={clients.length} label="Total Clients" tone="blue"/><Kpi icon="◇" n={packages.length} label="Active Campaigns" tone="red"/><Kpi icon="$" n={`${income.toLocaleString()} JOD`} label="Total Revenue" tone="blue"/><Kpi icon="☑" n={pending} label="Pending Tasks" tone="red"/></section>
  <section className="dashboardGrid">
   <div className="box clientsBox"><div className="boxHead"><h2><I>♟</I> Clients</h2><button className="add" onClick={()=>setTab('clients')}>＋ Add Client</button><button className="view" onClick={()=>setTab('clients')}>View All →</button></div><div className="filters"><div className="search mini">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search clients..."/></div><select><option>All Status</option></select></div><div className="clientTable"><div className="tr th"><span>Logo</span><span>Name</span><span>Package</span><span>Status</span><span>Start Date</span><span>End Date</span><span>Actions</span></div>{filtered.slice(0,8).map(c=><div className="tr" key={c.id}><span>{c.logo_url?<img src={c.logo_url}/>:<i className="letter">{c.name?.[0]}</i>}</span><b>{c.name}</b><span><i className="tag">{c.package_name||'—'}</i></span><span><i className="status">Active</i></span><span>{fmt(c.start_date)}</span><span>{fmt(c.end_date)}</span><span className="tableActions"><button onClick={()=>edit('clients',c,['name','start_date','end_date','contract_value','outstanding','phone'])}>✎</button><button onClick={()=>del('clients',c.id)}>♲</button></span></div>)}</div></div>
   <div className="rightCol"><div className="box packagesBox"><div className="boxHead"><h2><I>◇</I> Packages</h2><button className="add" onClick={()=>setTab('packages')}>＋ Add Package</button><button className="view" onClick={()=>setTab('packages')}>View All →</button></div><div className="packageCards">{packages.slice(0,3).map((p,i)=><article key={p.id}><h3>{p.name}</h3><strong className={i===2?'redtxt':''}>{p.price??'-'} <small>JOD</small></strong><ul><li>✓ {p.posts_target||0} Posts</li><li>✓ {p.reels_target||0} Reels</li><li>✓ {p.daily_story?'1 Daily Story':'Full Page Management'}</li></ul>{p.image_url?<img src={p.image_url}/>:<div className="packagePlaceholder"/>}<div><button onClick={()=>edit('packages',p,['name','price','posts_target','reels_target'])}>Edit</button><button className="delete" onClick={()=>del('packages',p.id)}>Delete</button></div></article>)}</div></div>
    <div className="box activityBox"><div className="boxHead"><h2><I>◴</I> Recent Activity</h2><button className="view" onClick={()=>setTab('activity')}>View All →</button></div>{(logs.length?logs:tasks).slice(0,5).map((x:any,i)=><div className="activityRow" key={x.id||i}><i>{['♟','☑','◇','▧','◴'][i%5]}</i><span>{x.user_name?`${x.user_name} ${x.action} ${x.entity_type} (${x.entity_name||''})`:`New task created for ${cname(x.client_id)}`}</span><time>{x.created_at?new Date(x.created_at).toLocaleString():fmt(x.due_date)}</time></div>)}</div>
   </div>
  </section>
 </div>}
 function Kpi({icon,n,label,tone}:{icon:string,n:any,label:string,tone:string}){return <div className={`kpi ${tone}`}><div className="kicon">{icon}</div><div><strong>{n}</strong><span>{label}</span></div><b>↗ +14%</b><i/></div>}
 function Page(){return <div className="page"><div className="pageTitle"><h1>{pageTitle[tab]}</h1><p>DH Agency management workspace</p></div>{tab==='clients'&&<Clients/>}{tab==='packages'&&<Packages/>}{tab==='tasks'&&<Tasks/>}{tab==='finance'&&<Finance/>}{tab==='calendar'&&<Calendar/>}{tab==='team'&&<Team/>}{tab==='activity'&&<Activity/>}{tab==='content'&&<Empty title="Content" text="Content planning and production workspace"/>}{tab==='settings'&&<Empty title="Settings" text="DH Manager workspace settings"/>}</div>}
 function Clients(){return <div className="box pageBox"><div className="boxHead"><h2>Clients</h2><span className="view">ADD • EDIT • DELETE • IMAGE</span></div><div className="form"><input placeholder="Client name" value={client.name} onChange={e=>setClient({...client,name:e.target.value})}/><select value={client.package_id} onChange={e=>setClient({...client,package_id:e.target.value})}><option value="">Choose package</option>{packages.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><input type="date" value={client.start_date} onChange={e=>setClient({...client,start_date:e.target.value})}/><input type="date" value={client.end_date} onChange={e=>setClient({...client,end_date:e.target.value})}/><input type="number" placeholder="Contract value" value={client.contract_value} onChange={e=>setClient({...client,contract_value:e.target.value})}/><input type="number" placeholder="Outstanding" value={client.outstanding} onChange={e=>setClient({...client,outstanding:e.target.value})}/><input placeholder="Phone" value={client.phone} onChange={e=>setClient({...client,phone:e.target.value})}/><input type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f)try{setClient({...client,logo_url:await upload(f,'clients')})}catch(x:any){alert(x.message)}}}/><button className="add" onClick={()=>{const p=packages.find(x=>x.id===client.package_id);add('clients',{...client,package_id:client.package_id||null,package_name:p?.name||null,contract_value:client.contract_value===''?null:Number(client.contract_value),outstanding:client.outstanding===''?null:Number(client.outstanding),logo_url:client.logo_url||null,status:'active'},()=>setClient({name:'',package_id:'',start_date:today(),end_date:'',contract_value:'',outstanding:'',phone:'',logo_url:''}))}}>＋ Add Client</button></div><div className="clientTable full"><div className="tr th"><span>Logo</span><span>Name</span><span>Package</span><span>Status</span><span>Start Date</span><span>End Date</span><span>Actions</span></div>{clients.map(c=><div className="tr" key={c.id}><span>{c.logo_url?<img src={c.logo_url}/>:<i className="letter">{c.name?.[0]}</i>}</span><b>{c.name}</b><span><i className="tag">{c.package_name||'—'}</i></span><span><i className="status">Active</i></span><span>{fmt(c.start_date)}</span><span>{fmt(c.end_date)}</span><span className="tableActions"><button onClick={()=>edit('clients',c,['name','start_date','end_date','contract_value','outstanding','phone'])}>✎</button><button onClick={()=>del('clients',c.id)}>♲</button></span></div>)}</div></div>}
 function Packages(){return <div className="box pageBox"><div className="form"><input placeholder="Package name" value={pkg.name} onChange={e=>setPkg({...pkg,name:e.target.value})}/><input type="number" placeholder="Price" value={pkg.price} onChange={e=>setPkg({...pkg,price:e.target.value})}/><input type="number" placeholder="Posts" value={pkg.posts_target} onChange={e=>setPkg({...pkg,posts_target:e.target.value})}/><input type="number" placeholder="Reels" value={pkg.reels_target} onChange={e=>setPkg({...pkg,reels_target:e.target.value})}/><input type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f)try{setPkg({...pkg,image_url:await upload(f,'packages')})}catch(x:any){alert(x.message)}}}/><button className="add" onClick={()=>add('packages',{...pkg,price:pkg.price===''?null:Number(pkg.price),posts_target:Number(pkg.posts_target),reels_target:Number(pkg.reels_target),image_url:pkg.image_url||null},()=>setPkg({name:'',price:'',posts_target:'0',reels_target:'0',daily_story:false,image_url:''}))}>＋ Add Package</button></div><div className="packageCards large">{packages.map(p=><article key={p.id}><h3>{p.name}</h3><strong>{p.price??'-'} <small>JOD</small></strong><ul><li>✓ {p.posts_target} Posts</li><li>✓ {p.reels_target} Reels</li></ul>{p.image_url?<img src={p.image_url}/>:<div className="packagePlaceholder"/>}<div><button onClick={()=>edit('packages',p,['name','price','posts_target','reels_target'])}>Edit</button><button className="delete" onClick={()=>del('packages',p.id)}>Delete</button></div></article>)}</div></div>}
 function Tasks(){return <SimpleForm title="Tasks" form={<><input placeholder="Task" value={task.title} onChange={e=>setTask({...task,title:e.target.value})}/><select value={task.client_id} onChange={e=>setTask({...task,client_id:e.target.value})}><option value="">General</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input type="date" value={task.due_date} onChange={e=>setTask({...task,due_date:e.target.value})}/><select value={task.priority} onChange={e=>setTask({...task,priority:e.target.value})}><option value="normal">Normal</option><option value="medium">Medium</option><option value="high">High</option></select><button className="add" onClick={()=>add('tasks',{...task,client_id:task.client_id||null,status:'pending'},()=>setTask({title:'',client_id:'',due_date:today(),priority:'normal'}))}>＋ Add</button></>} rows={tasks.map(t=><DataRow key={t.id} title={t.title} sub={`${cname(t.client_id)} • ${fmt(t.due_date)}`} onEdit={()=>edit('tasks',t,['title','due_date','priority'])} onDelete={()=>del('tasks',t.id)}/>)}/>}
 function Finance(){return <SimpleForm title="Finance" form={<><input placeholder="Description" value={tx.title} onChange={e=>setTx({...tx,title:e.target.value})}/><select value={tx.type} onChange={e=>setTx({...tx,type:e.target.value})}><option value="income">Income</option><option value="expense">Expense</option><option value="freelancer">Freelancer</option></select><input type="number" placeholder="Amount" value={tx.amount} onChange={e=>setTx({...tx,amount:e.target.value})}/><button className="add" onClick={()=>add('financial_transactions',{...tx,transaction_date:today(),client_id:null,amount:Number(tx.amount||0)},()=>setTx({title:'',client_id:'',type:'income',amount:'',transaction_date:today()}))}>＋ Add</button></>} rows={txs.map(x=><DataRow key={x.id} title={`${x.title} — ${x.amount} JOD`} sub={fmt(x.transaction_date)} onEdit={()=>edit('financial_transactions',x,['title','amount','transaction_date'])} onDelete={()=>del('financial_transactions',x.id)}/>)}/>}
 function Calendar(){return <SimpleForm title="Calendar" form={<><input placeholder="Appointment" value={appt.title} onChange={e=>setAppt({...appt,title:e.target.value})}/><input type="date" value={appt.appointment_date} onChange={e=>setAppt({...appt,appointment_date:e.target.value})}/><input type="time" value={appt.appointment_time} onChange={e=>setAppt({...appt,appointment_time:e.target.value})}/><button className="add" onClick={()=>add('appointments',{...appt,appointment_time:appt.appointment_time||null,client_id:null,status:'pending'},()=>setAppt({title:'',client_id:'',appointment_date:today(),appointment_time:''}))}>＋ Add</button></>} rows={appts.map(a=><DataRow key={a.id} title={a.title} sub={`${fmt(a.appointment_date)} ${a.appointment_time||''}`} onEdit={()=>edit('appointments',a,['title','appointment_date','appointment_time'])} onDelete={()=>del('appointments',a.id)}/>)}/>}
 function Team(){return <div className="box pageBox"><div className="teamGrid">{profiles.map(p=><article className="teamCard" key={p.id}><div className="profilePic big">{(p.display_name||'U')[0]}</div><h3>{p.display_name||'User'}</h3><span>{p.role||'TEAM'}</span></article>)}</div></div>}
 function Activity(){return <div className="box pageBox">{logs.map((x:any)=><div className="activityRow" key={x.id}><i>◴</i><span>{x.user_name} {x.action} {x.entity_type} ({x.entity_name||''})</span><time>{x.created_at?new Date(x.created_at).toLocaleString():''}</time></div>)}</div>}
 function Empty({title,text}:{title:string,text:string}){return <div className="box empty"><I>◇</I><h2>{title}</h2><p>{text}</p></div>}
 function SimpleForm({title,form,rows}:{title:string,form:any,rows:any}){return <div className="box pageBox"><div className="boxHead"><h2>{title}</h2></div><div className="form">{form}</div><div className="dataList">{rows}</div></div>}
 function DataRow({title,sub,onEdit,onDelete}:{title:string,sub:string,onEdit:()=>void,onDelete:()=>void}){return <div className="dataRow"><div><b>{title}</b><span>{sub}</span></div><div><button onClick={onEdit}>Edit</button><button className="delete" onClick={onDelete}>Delete</button></div></div>}
}
