'use client'
import {useEffect,useMemo,useState} from 'react'
import {useRouter} from 'next/navigation'
import {supabase} from '../lib/supabase'
const today=()=>new Date().toISOString().slice(0,10), N=(x:any)=>Number(x||0)
const validDate=(v:any)=>{
  if(!v || typeof v!=='string') return null
  if(!/^\d{4}-\d{2}-\d{2}$/.test(v)) return null
  const [y,m,d]=v.split('-').map(Number)
  if(y<1900 || y>2100 || m<1 || m>12 || d<1 || d>31) return null
  const dt=new Date(`${v}T00:00:00`)
  if(Number.isNaN(dt.getTime())) return null
  if(dt.getFullYear()!==y || dt.getMonth()+1!==m || dt.getDate()!==d) return null
  return v
}
const dateOrNull=(v:any)=>validDate(v)
export default function Home(){
 const router=useRouter(); const [tab,setTab]=useState('overview'),[loading,setLoading]=useState(true),[me,setMe]=useState<any>(null)
 const [profiles,setProfiles]=useState<any[]>([]),[clients,setClients]=useState<any[]>([]),[packages,setPackages]=useState<any[]>([]),[tasks,setTasks]=useState<any[]>([]),[txs,setTxs]=useState<any[]>([]),[appts,setAppts]=useState<any[]>([])
 const [client,setClient]=useState<any>({name:'',package_id:'',start_date:today(),end_date:'',contract_value:'',outstanding:'',phone:'',logo_url:''})
 const [pkg,setPkg]=useState<any>({name:'',price:'',posts_target:'0',reels_target:'0',daily_story:false,image_url:''})
 const [task,setTask]=useState<any>({title:'',client_id:'',due_date:today(),priority:'normal'})
 const [tx,setTx]=useState<any>({title:'',client_id:'',type:'income',amount:'',transaction_date:today()})
 const [appt,setAppt]=useState<any>({title:'',client_id:'',appointment_date:today(),appointment_time:''})
 const cname=(id:any)=>clients.find(c=>c.id===id)?.name||'عام'
 async function load(){const {data:{session}}=await supabase.auth.getSession();if(!session){router.replace('/login');return}
  const [p,c,g,t,f,a]=await Promise.all([supabase.from('profiles').select('*'),supabase.from('clients').select('*').order('created_at'),supabase.from('packages').select('*').order('created_at'),supabase.from('tasks').select('*').order('due_date'),supabase.from('financial_transactions').select('*').order('transaction_date',{ascending:false}),supabase.from('appointments').select('*').order('appointment_date')])
  setProfiles(p.data||[]);setMe((p.data||[]).find((x:any)=>x.id===session.user.id)||{display_name:session.user.email});setClients(c.data||[]);setPackages(g.data||[]);setTasks(t.data||[]);setTxs(f.data||[]);setAppts(a.data||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 async function add(table:string,p:any,reset:()=>void){const {error}=await supabase.from(table).insert(p);if(error)return alert(error.message);reset();load()}
 async function del(table:string,id:string){if(!confirm('متأكد من الحذف؟'))return;const {error}=await supabase.from(table).delete().eq('id',id);if(error)return alert(error.message);load()}
 async function edit(table:string,row:any,fields:string[]){let p:any={};for(const k of fields){const v=prompt(`تعديل ${k}`,row[k]??'');if(v===null)continue
  if(['start_date','end_date','due_date','transaction_date','appointment_date'].includes(k)){
    if(v!=='' && !validDate(v)){alert(`التاريخ غير صحيح: ${v}\nاستخدم YYYY-MM-DD`);return}
    p[k]=dateOrNull(v); continue
  }
  p[k]=['price','amount','contract_value','outstanding','posts_target','reels_target'].includes(k)?(v===''?null:Number(v)):v
}if(!Object.keys(p).length)return;const {error}=await supabase.from(table).update(p).eq('id',row.id);if(error)return alert(error.message);load()}
 async function upload(file:File,folder:string){const ext=file.name.split('.').pop();const path=`${folder}/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from('dh-manager-media').upload(path,file);if(error)throw error;return supabase.storage.from('dh-manager-media').getPublicUrl(path).data.publicUrl}
 const income=txs.filter(x=>x.type==='income').reduce((s,x)=>s+N(x.amount),0),expenses=txs.filter(x=>x.type!=='income').reduce((s,x)=>s+N(x.amount),0)
 if(loading)return <main className="shell">جاري تحميل DH Manager...</main>
 const tabs=[['overview','الرئيسية'],['clients','العملاء'],['packages','الباقات'],['tasks','المهام'],['finance','المالية'],['calendar','المواعيد']]
 return <main className="shell">
 <aside className="sidebar">
  <div className="sideLogo"><img src="/dh-logo-transparent.png"/></div>
  <nav className="nav">{[['overview','⌂','Overview'],['clients','♙','Clients'],['packages','◇','Packages'],['tasks','✓','Tasks'],['finance','$','Finance'],['calendar','□','Calendar']].map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}><span className="navIcon">{x[1]}</span>{x[2]}</button>)}</nav>
  <div className="sideQuote"><em>“Better Content<br/>Bigger Opportunities”</em><small>DH AGENCY • 2026</small></div>
 </aside>
 <div className="main">
  <header className="topbar"><div className="search"><input placeholder="Search clients, tasks, content, campaigns..."/><kbd>⌘ K</kbd></div><div className="topActions"><button className="iconBtn">☼</button><button className="iconBtn">♧</button><div className="user"><div className="avatar">{(me?.display_name||'H')[0]}</div><div><b>{me?.display_name||'HATEM AL DASUQI'}</b><div className="muted">{me?.role||'Owner'}</div></div></div><button className="btn" onClick={async()=>{await supabase.auth.signOut();router.replace('/login')}}>Logout</button></div></header>
  {tab==='overview'&&<>
   <section className="hero"><div className="heroText"><h1>Good evening, <span>Hatem</span> 👋</h1><p>Discipline today, results tomorrow.</p><div className="quote">“Better content. Bigger opportunities.”</div></div><div className="dateBox">▣ &nbsp; {new Date().toLocaleDateString('en-GB',{weekday:'short',day:'2-digit',month:'short',year:'numeric'})}</div></section>
   <div className="quick"><button className="btn gold">＋ Create</button><button className="btn" onClick={()=>setTab('clients')}>♙ &nbsp; Client</button><button className="btn" onClick={()=>setTab('tasks')}>☑ &nbsp; Task</button><button className="btn">▧ &nbsp; Content</button><button className="btn">⌁ &nbsp; Campaign</button><button className="btn" onClick={()=>setTab('finance')}>▤ &nbsp; Invoice</button></div>
   <section className="metrics"><div className="metric"><div className="metricTop"><div className="metricIcon">♟</div><div><small>Active Clients</small><strong>{clients.filter(x=>x.status!=='inactive').length}</strong></div></div><div className="trend">↗ +20% &nbsp; <span className="muted">vs last month</span></div></div><div className="metric"><div className="metricTop"><div className="metricIcon">$</div><div><small>Monthly Revenue</small><strong>{income.toLocaleString()} JOD</strong></div></div><div className="trend">↗ +32% &nbsp; <span className="muted">vs last month</span></div></div><div className="metric"><div className="metricTop"><div className="metricIcon">▥</div><div><small>Active Campaigns</small><strong>{Math.min(4,clients.length)}</strong></div></div><div className="trend">↗ +100% &nbsp; <span className="muted">vs last month</span></div></div><div className="metric"><div className="metricTop"><div className="metricIcon">☑</div><div><small>Pending Tasks</small><strong>{tasks.filter(x=>x.status!=='completed').length}</strong></div></div><div className="trend red">↗ +25% &nbsp; <span className="muted">vs last week</span></div></div></section>
   <section className="dashgrid"><div className="panel"><div className="panelHead"><div><h2>▥ &nbsp; Revenue Overview</h2><div className="panelSub">Track your monthly growth</div></div><button className="btn">Last 12 Months⌄</button></div><div className="chart"><div className="bars">{[18,24,31,40,48,56,61,55,50,65,70,84].map((h,i)=><div key={i} className={'bar '+(i===9?'hot':'')} style={{height:`${h}%`}}></div>)}</div></div></div><div className="panel"><div className="panelHead"><h2>Monthly Goal</h2><span className="money">Edit Goal</span></div><div className="goalWrap"><div className="ring"><b>{Math.min(100,Math.round(income/3000*100))}%</b></div><div className="goalText"><strong>{income.toLocaleString()} / 3,000 JOD</strong><div className="trend">Keep going! 🚀</div></div></div><div className="miniStats"><div><b>{Math.max(0,3000-income).toLocaleString()} JOD</b><span className="muted"> Remaining</span></div><div><b>73 Days</b><span className="muted"> Left</span></div></div></div><div className="panel quoteCard"><div className="q">Discipline<br/>today,<br/>results<br/>tomorrow.</div></div></section>
   <section className="bottomgrid"><div className="panel"><div className="panelHead"><h2>☑ &nbsp; Today’s Tasks</h2><span className="money">View All →</span></div><div className="list">{tasks.slice(0,5).map(t=><div className="row" key={t.id}><span>○</span><div className="grow"><b>{t.title}</b><span>{cname(t.client_id)} • {t.due_date||'-'}</span></div><span className={'pill '+(t.priority==='high'?'red':'')}>{t.priority}</span></div>)}{!tasks.length&&<div className="row"><div className="grow"><b>No pending tasks</b><span>Add a task to get started</span></div></div>}</div><button className="btn" style={{width:'100%',marginTop:10}} onClick={()=>setTab('tasks')}>＋ Add Task</button></div>
   <div className="panel"><div className="panelHead"><h2>♟ &nbsp; Recent Clients</h2><span className="money">View All →</span></div><div className="list">{clients.slice(0,5).map(c=><div className="row" key={c.id}>{c.logo_url?<img className="logo" src={c.logo_url}/>:<div className="avatar">{c.name?.[0]}</div>}<div className="grow"><b>{c.name}</b><span>{c.package_name||'No package'}</span></div><span className="pill green">{c.status||'Active'}</span></div>)}</div><button className="btn" style={{width:'100%',marginTop:10}} onClick={()=>setTab('clients')}>＋ Add New Client</button></div>
   <div className="panel"><div className="panelHead"><h2>▣ &nbsp; Upcoming Deadlines</h2><span className="money">View All →</span></div><div className="list">{clients.filter(c=>c.end_date).slice(0,5).map(c=><div className="row" key={c.id}><div className="avatar">{c.end_date?.slice(8,10)||'--'}</div><div className="grow"><b>{c.name}</b><span>Contract Ends • {c.end_date}</span></div><span className="pill">Due</span></div>)}</div></div></section>
  </>}
  {tab==='clients'&&<section className="section panel"><div className="panelHead"><h2>Clients</h2><span className="pill">ADD • EDIT • DELETE • IMAGE</span></div><div className="form"><input placeholder="Client name" value={client.name} onChange={e=>setClient({...client,name:e.target.value})}/><select value={client.package_id} onChange={e=>setClient({...client,package_id:e.target.value})}><option value="">Choose package</option>{packages.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><input type="date" value={client.start_date} onChange={e=>setClient({...client,start_date:e.target.value})}/><input type="date" value={client.end_date} onChange={e=>setClient({...client,end_date:e.target.value})}/><input type="number" placeholder="Contract value" value={client.contract_value} onChange={e=>setClient({...client,contract_value:e.target.value})}/><input type="number" placeholder="Outstanding" value={client.outstanding} onChange={e=>setClient({...client,outstanding:e.target.value})}/><input placeholder="Phone" value={client.phone} onChange={e=>setClient({...client,phone:e.target.value})}/><input type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f)try{setClient({...client,logo_url:await upload(f,'clients')})}catch(x:any){alert(x.message)}}}/><button className="btn gold" onClick={()=>{const p=packages.find(x=>x.id===client.package_id);add('clients',{...client,start_date:dateOrNull(client.start_date),end_date:dateOrNull(client.end_date),package_id:client.package_id||null,package_name:p?.name||null,contract_value:client.contract_value===''?null:Number(client.contract_value),outstanding:client.outstanding===''?null:Number(client.outstanding),logo_url:client.logo_url||null,status:'active'},()=>setClient({name:'',package_id:'',start_date:today(),end_date:'',contract_value:'',outstanding:'',phone:'',logo_url:''}))}}>Add Client</button></div><div className="cards">{clients.map(c=><article className="card" key={c.id}><div className="clientTop"><div>{c.logo_url?<img className="logo" src={c.logo_url}/>:<div className="avatar">{c.name?.[0]}</div>}<h3>{c.name}</h3></div><span className="pill">{c.package_name||'No package'}</span></div><p className="muted">{c.start_date||'-'} → {c.end_date||'-'}</p><div className="money">Contract: {c.contract_value??'-'} JD • Due: {c.outstanding??'-'} JD</div><div className="actions"><button className="btn" onClick={()=>edit('clients',c,['name','start_date','end_date','contract_value','outstanding','phone'])}>Edit</button><button className="btn danger" onClick={()=>del('clients',c.id)}>Delete</button></div></article>)}</div></section>}
  {tab==='packages'&&<section className="section panel"><h2>Packages</h2><div className="form"><input placeholder="Package name" value={pkg.name} onChange={e=>setPkg({...pkg,name:e.target.value})}/><input type="number" placeholder="Price" value={pkg.price} onChange={e=>setPkg({...pkg,price:e.target.value})}/><input type="number" placeholder="Posts" value={pkg.posts_target} onChange={e=>setPkg({...pkg,posts_target:e.target.value})}/><input type="number" placeholder="Reels" value={pkg.reels_target} onChange={e=>setPkg({...pkg,reels_target:e.target.value})}/><input type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f)try{setPkg({...pkg,image_url:await upload(f,'packages')})}catch(x:any){alert(x.message)}}}/><button className="btn gold" onClick={()=>add('packages',{...pkg,price:pkg.price===''?null:Number(pkg.price),posts_target:Number(pkg.posts_target),reels_target:Number(pkg.reels_target),image_url:pkg.image_url||null},()=>setPkg({name:'',price:'',posts_target:'0',reels_target:'0',daily_story:false,image_url:''}))}>Add Package</button></div><div className="cards">{packages.map(p=><article className="card" key={p.id}>{p.image_url&&<img className="pkgimg" src={p.image_url}/>}<h3>{p.name}</h3><div className="money">{p.price??'-'} JD</div><p>{p.posts_target} Posts • {p.reels_target} Reels</p><div className="actions"><button className="btn" onClick={()=>edit('packages',p,['name','price','posts_target','reels_target'])}>Edit</button><button className="btn danger" onClick={()=>del('packages',p.id)}>Delete</button></div></article>)}</div></section>}
  {tab==='tasks'&&<section className="section panel"><h2>Tasks</h2><div className="form"><input placeholder="Task" value={task.title} onChange={e=>setTask({...task,title:e.target.value})}/><select value={task.client_id} onChange={e=>setTask({...task,client_id:e.target.value})}><option value="">General</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input type="date" value={task.due_date} onChange={e=>setTask({...task,due_date:e.target.value})}/><select value={task.priority} onChange={e=>setTask({...task,priority:e.target.value})}><option value="normal">Normal</option><option value="medium">Medium</option><option value="high">High</option></select><button className="btn gold" onClick={()=>add('tasks',{...task,due_date:dateOrNull(task.due_date),client_id:task.client_id||null,status:'pending'},()=>setTask({title:'',client_id:'',due_date:today(),priority:'normal'}))}>Add</button></div><div className="list">{tasks.map(t=><div className="row" key={t.id}><div className="grow"><b>{t.title}</b><span>{cname(t.client_id)} • {t.due_date}</span></div><button className="btn" onClick={()=>edit('tasks',t,['title','due_date','priority'])}>Edit</button><button className="btn danger" onClick={()=>del('tasks',t.id)}>Delete</button></div>)}</div></section>}
  {tab==='finance'&&<section className="section panel"><h2>Finance</h2><div className="form"><input placeholder="Description" value={tx.title} onChange={e=>setTx({...tx,title:e.target.value})}/><select value={tx.type} onChange={e=>setTx({...tx,type:e.target.value})}><option value="income">Income</option><option value="expense">Expense</option><option value="freelancer">Freelancer</option></select><input type="number" placeholder="Amount" value={tx.amount} onChange={e=>setTx({...tx,amount:e.target.value})}/><button className="btn gold" onClick={()=>add('financial_transactions',{...tx,transaction_date:dateOrNull(tx.transaction_date)||today(),client_id:null,amount:Number(tx.amount||0)},()=>setTx({title:'',client_id:'',type:'income',amount:'',transaction_date:today()}))}>Add</button></div><div className="list">{txs.map(x=><div className="row" key={x.id}><div className="grow"><b>{x.title}</b><span>{x.transaction_date}</span></div><b className={x.type==='income'?'money':'red'}>{x.amount} JD</b><button className="btn" onClick={()=>edit('financial_transactions',x,['title','amount','transaction_date'])}>Edit</button><button className="btn danger" onClick={()=>del('financial_transactions',x.id)}>Delete</button></div>)}</div></section>}
  {tab==='calendar'&&<section className="section panel"><h2>Calendar</h2><div className="form"><input placeholder="Appointment" value={appt.title} onChange={e=>setAppt({...appt,title:e.target.value})}/><input type="date" value={appt.appointment_date} onChange={e=>setAppt({...appt,appointment_date:e.target.value})}/><input type="time" value={appt.appointment_time} onChange={e=>setAppt({...appt,appointment_time:e.target.value})}/><button className="btn gold" onClick={()=>add('appointments',{...appt,appointment_date:dateOrNull(appt.appointment_date)||today(),appointment_time:appt.appointment_time||null,client_id:null,status:'pending'},()=>setAppt({title:'',client_id:'',appointment_date:today(),appointment_time:''}))}>Add</button></div><div className="list">{appts.map(a=><div className="row" key={a.id}><div className="grow"><b>{a.title}</b><span>{a.appointment_date} {a.appointment_time}</span></div><button className="btn" onClick={()=>edit('appointments',a,['title','appointment_date','appointment_time'])}>Edit</button><button className="btn danger" onClick={()=>del('appointments',a.id)}>Delete</button></div>)}</div></section>}
 </div>
 </main>}
